packages/mangrove-solidity/README.md
packages/mangrove-solidity/config/custom-environment-variables.json

This commit uses a features of the node-config package (which is already used for reading configuration) to enable overriding part of the configuration using environment variables.
For now, only config.hardhat.networks.hardhat.chainId can be specified by the HARDHAT_NETWORK_CHAIN_ID env var. But it is straightforward to add more such env var config overrides.

mangrove-solidity: Add env var override of config parts

---

packages/cleaning-bot/src/MarketCleaner.ts
packages/mangrove.js/src/mangrove.ts
packages/mangrove.js/src/market.ts
packages/mangrove.js/src/types/index.ts
packages/obfiller-bot/src/OfferMaker.ts
packages/obfiller-bot/src/OfferTaker.ts

The Offer type was declared both places, but in slightly different ways.

mangrove.js: Move exported types from Market.ts to types/index.ts

---

.github/workflows/node.js.yml

Mangrove's git repos are public and anyone can make pull requests (PR's). Such PR's can contain arbitrary code, both regular code and workflow definitions. A malicious actor could therefore potentially use a PR to abuse our CI setup, e.g. by using compute/storage resources or leaking secrets.
Our CI setup must therefore treat external PR's with great care to avoid abuse.
GitHub Actions unfortunately does not provide a good framework or best practices for CI of external PR's in a secure manner. Our solution is therefore somewhat bespoke and clunky, but we deem it good enough and secure enough for now.
In overview, our approach is the following:
- Our workflow begin with a "guard" job which only allows the workflow to continue if the trigger is internal or an external PR that has been …

Fix CI for external PR's and introduce security guard job

---

.github/workflows/node.js.yml

Previously, the workflow was only cancelled. This caused the UI to signal that the PR was ready to merge though it hadn't been build or testet.
Failure is a bit draconian, but safer.

CI: Fail CI for external PR's not labelled 'safe to test'

---

packages/mangrove-solidity/doc/CNAME

GitHub habitually clobbers a dynamically configured CNAME
https://github.com/tschaub/gh-pages/issues/236

mangrove-solidity: Add static CNAME to doc

---

packages/mangrove.js/CHANGELOG.md
packages/mangrove.js/README.md
packages/mangrove.js/package.json
packages/mangrove.js/src/cli/commands/parrotCmd.ts
packages/mangrove.js/src/cli/commands/printCmd.ts
packages/mangrove.js/src/cli/commands/retractCmd.ts
packages/mangrove.js/src/cli/mgv.ts
packages/mangrove.js/src/tsconfig.json
packages/mangrove.js/tsconfig.json
yarn.lock

The CLI is now compiled and can be run without ts-node.
This also means that CI will complain if we forget to update it.
As the CLI includes package.json, we've had to move tsconfig.json to src/ and introduce a simpler one in the root of mangrove.js. Otherwise, the compiled files would be placed in dist/nodejs/src.
See the following link for more information: https://stackoverflow.com/a/61467483/16614325

mangrove.js: Improve CLI useability

---

packages/mangrove-solidity/package.json

Script `clean-this-package` should also remove old local deployments as well as hardhat artifacts.

mangrove-solidity: Improve clean-this-package

---

packages/mangrove.js/CHANGELOG.md
packages/mangrove.js/README.md
packages/mangrove.js/src/market.ts
packages/mangrove.js/src/semibook.ts
packages/mangrove.js/test/integration/semibook.integration.test.ts

Adds new `Market` options as specified in #121:
- `desiredPrice`: allows one to specify a price point of interest. This will cause the cache to initially load all offers with this price or better.
- `desiredVolume`: allows one to specify a volume of interest. This will cause the cache to initially load at least this volume (if available). The option uses the same specification as for `estimateVolume`: `desiredVolume: { given: 1, what: "base", to: "buy" }` will cause the asks semibook to be initialized with a volume of at least 1 base token.
Closes #121.

feat(market): Add options for initially loading offers matching desired volume or price

---

packages/mangrove.js/CHANGELOG.md
packages/mangrove.js/src/market.ts

This flag will be true if the order was only partially filled.

feat(market): Add `partialFill` flag to `OrderResult`

---

packages/mangrove-solidity/contracts/MgvLib.sol
packages/mangrove-solidity/contracts/MgvOfferMaking.sol
packages/mangrove-solidity/contracts/MgvOfferTaking.sol

* Clarified IMaker interface description
* Updated comments on `offerId` size (24->32bits)
* Indexed `taker` field in `OrderComplete`
* Use `checkGasprice` in `writeOffer`
+ replace `{out,in}bound_tkn` with `sor.{out,in}bound` to avoid new
Stack Too Deep error.

Apply Chainsecurity's suggestions following diff audit

---

packages/mangrove.js/CHANGELOG.md
packages/mangrove.js/package.json
packages/mangrove.js/src/util/logger.ts
yarn.lock

The logger has been stunted by removing the dependency to commonlib.js
as a temporary workaround for issue #220.
To avoid reverting a merge commit and the burden of maintaining that old feature branch,
we have opted to keep most of the logging code but only support simplified logging to console.
For references on why we want to avoid revert merge commits:
Long (Linus): https://github.com/git/git/blob/master/Documentation/howto/revert-a-faulty-merge.txt
Short: https://www.datree.io/resources/git-undo-merge

fix(logging): Remove dependency on commonlib.js as temp workaround for #220

---

.github/workflows/node.js.yml

There were two issues in the pull_request_target solution introduced in https://github.com/mangrovedao/mangrove/commit/68557b0a04e4558b1ac6a27c499c6da32a1d4da1:
1. `GIT_REF_TO_TEST` was incorrectly set to the target branch for _internal_ pull requests. For all pull requests, it is now set to the merge commit of the pull request.
2. We forgot to update all checkout steps to use the initially computed reference `GIT_REF_TO_TEST` to the commit that should be checked out. This meant that when the PR was run on a PR to `master` it was the code _already_ on `master` that was checked out and testet. This has now been fixed.

build: Fix logic for `GIT_REF_TO_TEST` and add missing ref to checkout steps

---

packages/bot-maker-noise/src/OfferMaker.ts

- Include reference price in log for posted offers 
- Force crash when offer posting fails 
- The Noise Maker bot seems to hang after an offer fails to post. As a quick workaround, we force the app to quit which will get Heroku to restart it.

feat!: Noise Maker bot improvements

---

packages/bot-maker-noise/src/index.ts

The bot seems to hang after undhandled rejections so we now quit and allow Heroku to restart it.

feat!: Exit the bot on unhandled rejections

---

.github/dependabot.yml

For now, @dontrolle handles dependabot as we are testing it out.

fix(ci): Assign dependabot reviewer dontrolle

---

packages/bot-taker-greedy/package.json
packages/bot-taker-greedy/src/OfferTaker.ts
packages/bot-taker-greedy/src/index.ts
yarn.lock

According to the Nodejs documentation, calling `process.exit()` is bad practice: https://nodejs.org/api/process.html#processexitcode
One risk is that any logs written before exiting may not be written.
The process shutdown logic has therefore been changed to stop all takers and thereby remove all work from the event loop which should cause Nodejs to shut down.
As part of this, the `OfferTaker` class has been changed to use ToadScheduler instead of an infinite loop with a `sleep` call; This is easier to stop immediately and more flexible (and we use it in other bots).

feat(Greedy Taker bot): Use Toad Scheduler instead of `sleep` and rely on nodejs shutdown

---

packages/bot-cleaning/src/index.ts

Let NodeJS handle shutdown when there's no more work instead of calling `process.exit`.
This allows any logging to complete before closing down.

feat(Cleaning Bot): Shut down gracefully

---

packages/bot-template/src/index.ts

Let NodeJS handle shutdown when there's no more work instead of calling `process.exit`.
This allows any logging to complete before closing down.

feat(Template Bot): Graceful shutdown

---

packages/bot-updategas/src/index.ts

Let NodeJS handle shutdown when there's no more work instead of calling `process.exit`.
This allows any logging to complete before closing down.

feat(Gas Updater): Graceful shutdown

---

packages/mangrove.js/package.json
yarn.lock

Is required by a few test-scripts. Allows us to control version explicitly.

chore: Add minimist as an explicit dev-dependency

---

packages/bot-cleaning/src/index.ts
packages/bot-cleaning/test/integration/marketCleaner.integration.tests.ts
packages/bot-maker-noise/src/index.ts
packages/bot-template/src/index.ts
packages/bot-updategas/src/index.ts
packages/hardhat-utils/mocha/hooks/integration-test-root-hooks.js
packages/mangrove-solidity/scripts/demo.js
packages/mangrove-solidity/scripts/governance/MGVActivateMarkets.js
packages/mangrove-solidity/scripts/helper.js
packages/mangrove-solidity/scripts/mumbai/prodTests/Credit/creditTester.js
packages/mangrove-solidity/scripts/mumbai/prodTests/MM/fundMango.js
packages/mangrove-solidity/scripts/mumbai/prodTests/MM/initializeMango.js
packages/mangrove-solidity/scripts/mumbai/prodTests/MM/shiftMango.js
packages/mangrove-solidity/scripts/mumbai/prodTests/MM/shutdownMango.js
packages/mangrove-solidity/scripts/mumbai/prodTests/OasisLike/OasisLikeActivateMarkets.js
packages/mangrove-solidity/scripts/mumbai/prodTests/OfferProxy/OfferProxyActivateMarkets.js
packages/mangrove-solidity/scripts/mumbai/prodTests/OfferProxy/PostOfferViaProxy.js
packages/mangrove.js/CHANGELOG.md
packages/mangrove.js/src/cli/commands/retractCmd.ts
packages/mangrove.js/src/eth.ts
packages/mangrove.js/test/scripts/mgvServer.js
packages/mangrove.js/test/scripts/obFiller.js
packages/mangrove.js/test/scripts/obViewer.js
packages/mangrove.js/test/scripts/tester.js

`getDefaultProvider` provides more flexibility as it detects the protocol and constructs an appropriate provider. Thus by using that instead of `new WebSocketProvider` or `new JsonRpcProvider` the user/caller is free to select the protocol.

feat: Use `ethers.getDefaultProvider` instead of limited protocol-specific providers

---

packages/mangrove.js/writeTestDeploymentFiles.ts

Write hardhatAddresses.json in the format that prettier likes to prevent constant whitespace-flux in the hardhatAddresses.json-file.
Note, that we knowingly accept writing the *nix-specific linebreak, `\n`. For one, this codebase is mainly tested to work on *nix; secondly, the alternative would be to accept possible fluctuation in the line endings of `hardAddresses.json`. This does not seem a good solution either. Ultimately, in the long run the `hardhatAddresses.json`-file will most likely not survive, so we accept this solution for now.

chore(mangrove.js): Prettify hardhatAddresses.json

---

packages/mangrove-solidity/test/test-defensive.js

We've seen failing builds on `master` which *may* stem from a possible flaky test in `test-defensive.js`. It's disrupting dev flow, so we're uncommenting the test on `master`, while we're investigating.

test(mangrove-solidity): Disable posbly flaky test

---

packages/mangrove.js/CHANGELOG.md
packages/mangrove.js/src/util/logger.ts

It can be turned on by calling `enableLogging()` in `util/logger`.
This is a temporary workaround to prevent unwanted logging to the console until issue #220 is fixed.

feat!(logging): Disable logging by default

---

packages/mangrove-solidity/config/custom-environment-variables.json

Hardhat logging for the Hardhat network can now be turned on/off by setting the env var `HARDHAT_NETWORK_LOGGING_ENABLED` to `true`/`false`.

feat: Control Hardhat network logging with `HARDHAT_NETWORK_LOGGING_ENABLED` env var

---

packages/bot-maker-noise/src/OfferMaker.ts
packages/bot-taker-greedy/src/OfferTaker.ts
packages/bot-updategas/src/GasUpdater.ts
packages/mangrove.js/src/liquidityProvider.ts
packages/mangrove.js/src/mangrove.ts
packages/mangrove.js/src/market.ts
packages/mangrove.js/src/offerLogic.ts

big.js can be configured a single time in mangrove.js.
Issue: if users import parts of mangrove.js directly (but don't import the Mangrove class), the big.js instance will not be properly configured.
edit: addresses #136

Only one big.js import

---

packages/bot-cleaning/package.json
packages/bot-maker-noise/package.json
packages/bot-taker-greedy/package.json
packages/bot-template/package.json
packages/bot-updategas/package.json
packages/faucet/package.json
packages/mangrove-solidity/package.json
packages/mangrove.js/package.json
yarn.lock

Some workflows around the dependabot behaved *not* according to plan. They've been disabled and this PR seeks to fix the damage done.

build(deps): Fix problems due to misbehaving dependabot

---

.github/workflows/node.js.yml
packages/faucet/hardhat.config.js

Also,  change the workflow to consistently handle package working directories:
For historical reasons, the default working directory was `packages/mangrove-solidity` and the jobs for that package therefore didn't specify a working package.
However, this adds unnecessary complexity, resulting in issues like the one fixed in @556e3af.
This commit therefore removes the default working directory and makes it explicit for the `mangrove-solidity` jobs.

fix: Use the right working directory when building the faucet package

---

packages/mangrove-solidity/contracts/test/lib/MangroveTest.sol
packages/mangrove-solidity/contracts/test/lib/Test2.sol
packages/mangrove-solidity/contracts/test/strategies/Guaave.t.sol
packages/mangrove-solidity/contracts/test/toy_strategies/AaveLender.t.sol

new `savePrank/restorePrank` test methods can save the current prank and call e.g. view functions without disrupting the current pranking situation.
Immediately useful with `cash`, which previously relied on [stdStorage](https://github.com/foundry-rs/forge-std/blob/master/src/Test.sol) and only worked on `TestToken`s, and can now just do
```solidity
savePrank();
uint decimals = t.decimals();
restorePrank();
```

feat(test): save/restore pranks, apply to cash()

---

packages/mangrove-solidity/package.json
packages/mangrove.js/package.json
yarn.lock

Also upped the available memory for JavaScript heap when building mangrove.js.
Consequential changes from https://github.com/mangrovedao/mangrove/pull/541 related to the epic https://github.com/mangrovedao/mangrove-tasks/issues/129

fix(build)!: Change mangrove-solidity local tests to use .env.local.test

---

foundry.toml

Remove these warnings
```
warning: Unknown section [default] found in ../../foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead or run `forge config --fix`.
warning: Unknown section [polygon] found in ../../foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.polygon] instead or run `forge config --fix`.
```

fix(foundry): Fixup foundry.toml format

---

README.md
packages/mangrove.js/package.json

VSCode appends a --require /very/long/path/extensions/ms-vscode.js-debug/src/bootloader.bundle.js to NODE_OPTIONS which I accidentally overrode when increasing JS heap memory. Now we no longer override but use cmd line options instead.

fix(test): Don't override NODE_OPTIONS's vscode bootloader

---

packages/bot-cleaning/src/MarketCleaner.ts
packages/mangrove.js/src/market.ts
packages/mangrove.js/src/util/trade.ts
packages/mangrove.js/test/integration/market.integration.test.ts

Add the ability to get raw parameter for sniping to use for callStatic and estimateGas methods.
We earlier decided to use number for max gas, that limits the max amount of gas we can pass in.
bot-cleaning is updated to use new api.
This completes #113  .

feat(snipe): Allow retrieval of raw parameters to send to contracts

---

packages/commonlib.js/src/index.ts
packages/commonlib.js/tsconfig.json
packages/mangrove.js/esbuild.mjs
packages/mangrove.js/package.json
packages/mangrove.js/tsconfig.json

Follow-up to https://github.com/mangrovedao/mangrove/pull/657
* Switch to iife bundling for esbuild - esbuild and rollup behave differently for some exports, and as commented in https://github.com/evanw/esbuild/issues/1182 we can work around this issue with a custom footer to avoid having to change the web-app's way of importing our bundle.
* Enable tsconfig flags which ensures esbuild works and make consequential changes.
* Switch to TypeScript for esbuild
* Run tscbuild and esbuild in parallel

feat(bundling): Make esbuild use TypeScript when bundling

---

.github/workflows/automerge-dependabot-prs.yml
.github/workflows/node.js.yml
.github/workflows/update-dependabot-prs.yml

* fix(ci): Dependabot workflow should only trigger for select branches
* feat(ci): Verify mgv cli can start as part of checks
* fix(ci): Make coveralls use actual HEAD commit
* The checkout of the push branch may not actually check out the GITHUB_SHA that triggered the workflow, a newer one may be checked out instead. We retrieve the right one by using git.
* feat(ci): Add solidity code coverage to push trigger
* Note: we currently run it from the root; otherwise, the coverage reporting cannot find our contracts. This may be related to
https://github.com/foundry-rs/foundry/issues/2915 . Also, we add flags to coveralls in an attempt to separate the reports.

feat(ci): Fix race in coveralls, add solidity coverage, check mgv cli, improve dependabot triggers

---

packages/mangrove-solidity/script/MangroveJs.s.sol
packages/mangrove-solidity/script/lib/MangroveDeployer.sol
packages/mangrove-solidity/src/periphery/MangroveOrder.sol
packages/mangrove-solidity/src/periphery/MangroveOrderEnriched.sol
packages/mangrove-solidity/src/periphery/MgvCleaner.sol
packages/mangrove-solidity/src/periphery/MgvReader.sol
packages/mangrove-solidity/src/strategies/MangroveOffer.sol
packages/mangrove-solidity/src/strategies/offer_forwarder/OfferForwarder.sol
packages/mangrove-solidity/src/strategies/offer_forwarder/abstract/Forwarder.sol
packages/mangrove-solidity/src/strategies/offer_forwarder/abstract/PersistentForwarder.sol
packages/mangrove-solidity/src/strategies/offer_maker/OfferMaker.sol
packages/mangrove-solidity/src/strategies/offer_maker/abstract/Direct.sol
packages/mangrove-solidity/src/strategies/offer_maker/abstract/Persistent.sol
packages/mangrove-solidity/src/toy_strategies/offer_forwarder/OasisLike.sol
packages/mangrove-solidity/src/toy_strategies/offer_forwarder/OfferProxy.sol
packages/mangrove-solidity/src/toy_strategies/offer_maker/Ghost.sol
packages/mangrove-solidity/src/toy_strategies/offer_maker/cash_management/AdvancedAaveRetail.sol
packages/mangrove-solidity/src/toy_strategies/offer_maker/cash_management/SimpleAaveRetail.sol
packages/mangrove-solidity/test/strategies/unit/MakerPermissions.t.sol
packages/mangrove-solidity/test/strategies/unit/MangroveOffer.t.sol
packages/mangrove-solidity/test/strategies/unit/OfferForwarder.t.sol
packages/mangrove-solidity/test/strategies/unit/OfferLogic.t.sol
packages/mangrove-solidity/test/toy_strategies/AaveLender.t.sol

IMHO MGV and _MGV should be changed to be mixedCase. I am a bit unsure whether _mgv should stay and be applied all over. We seem to use a mix of _ and not for parameter names. I see, e.g., https://ethereum.stackexchange.com/questions/56443/what-does-mean-before-a-variable-name mentions that some do it for all parameters to avoid shadowing. We currently do it when there are collisions but also sometimes when there is not.
I have not changed all tests.

MGV, _MGV and _mgv to mgv in ctors

---

packages/mangrove-solidity/preprocessing/structs.js
packages/mangrove-solidity/src/MgvOfferMaking.sol
packages/mangrove-solidity/src/periphery/MangroveOrder.sol
packages/mangrove-solidity/test/core/MakerOperations.t.sol
packages/mangrove-solidity/test/core/Scenarii.t.sol
packages/mangrove-solidity/test/lib/MangroveTest.sol

We mostly stick to using order book for our books with bids and aks. However, in some places we used offer book instead. We now use order book everywhere.

fix(doc): offer book -> order book

---

packages/mangrove-solidity/src/periphery/MangroveOrder.sol
packages/mangrove-solidity/test/periphery/MgvOrder.t.sol

Need to check
- moving the transfer of market order residual earlier
- always using router to transfer ERC to msg.sender's reserve (in case the reserve is not EOA)
- invariants in the comments do hold and are clear

Invariant annotations + refactoring

---

packages/bot-failing-offer/test/integration/failingOffer.integration.test.ts
packages/bot-taker-greedy/src/OfferTaker.ts
packages/mangrove.js/CHANGELOG.md
packages/mangrove.js/src/market.ts
packages/mangrove.js/src/util/tradeEventManagement.ts
packages/mangrove.js/test/integration/market.integration.test.ts
packages/mangrove.js/test/integration/restingOrder.integration.test.ts
packages/mangrove.js/test/unit/tradeEventManagement.unit.test.ts

It's a bounty from the taker's (who's buying or selling) perspective, so makes more sense to call it that.

refactor(mangrove.js): Rename penalty to bounty in Market.Summary

---

.github/workflows/node.js.yml

The upload of the test report would fail if any tests had failed. This had the annoying consequence that when clicking a failed job in GitHub Actions, it would scroll to the test report step instead of to the logs of the failing test itself.
Now the test report steps succeed even if any tests failed. The job will still fail in that case, so the flow of the workflow is unchanged.

CI: Don't fail test report steps

---

packages/mangrove.js/package.json
yarn.lock

Reverts mangrovedao/mangrove#649 as this upgrade requires code changes in mangrove.js

Revert "build(deps-dev): Bump chalk from 4.1.2 to 5.0.1"

---

packages/bot-cleaning/.env.local.example
packages/bot-cleaning/README.md
packages/bot-failing-offer/.env.local.example
packages/bot-failing-offer/README.md
packages/bot-maker-noise/README.md
packages/bot-taker-greedy/.env.local.example
packages/bot-taker-greedy/README.md
packages/bot-template/.env.local.example
packages/bot-template/README.md
packages/bot-updategas/.env.local.example
packages/bot-updategas/README.md
packages/bot-utils/.env.local.example
packages/bot-utils/README.md
packages/bot-utils/src/setup.ts

The node URL does not need to point to an Ethereum node, but an Ethereum-compatible JSON-RPC node, so the old name was confusing.

refactor!(bots): Replace ETHEREUM_NODE_URL with RPC_NODE_URL in all bots

---

packages/mangrove.js/CHANGELOG.md
packages/mangrove.js/src/market.ts
packages/mangrove.js/src/util/trade.ts
packages/mangrove.js/test/integration/market.integration.test.ts
packages/mangrove.js/test/unit/trade.unit.test.ts

`market.{buy|sell}` allowed `price` to be set to `null` which meant "accept any price" (= simulate a market order). This is dangerous, as such tx's are likely to be sandwich attacked:
1. Attacker borrows liquidity to front-run the victim
2. Attacker buys/sells the requested volume on Mangrove and inserts an offer at the top of the book with the requested volume and a price that is just a tiny bit better than the remainder on the book
3. Victim's tx is executed and buys the attacker's offer
4. Attacker repays the loan and pockets the difference between the borrowed amount and what the victim paid.
While we cannot prevent users from sending such orders, it should not be encouraged in the API. Therefore this commit removes the feature.
At a later stage we can add safer semantics for …

feat!(market): Remove dangerous behaviour when price is null

---

packages/bot-cleaning/test/integration/marketCleaner.integration.test.ts
packages/bot-failing-offer/test/integration/failingOffer.integration.test.ts
packages/bot-template/test/integration/templateBot.integration.test.ts
packages/bot-updategas/test/integration/gasUpdater.integration.test.ts
packages/mangrove.js/package.json
packages/mangrove.js/src/util/node.ts
packages/mangrove.js/src/util/test/mgvIntegrationTestUtil.ts
packages/mangrove.js/src/util/test/mochaHooks.ts
yarn.lock

Integration tests run against an anvil instance. We use snapshots and in `beforeEach` we revert to a previous, good, snapshot before starting each test.
However, the prior test can have outstanding RPC requests towards the anvil instance and these can complete _after_ the revert, causing changes to anvil state.
We now proxy all requests through a proxy and close it for further requests and wait for outstanding requests before reverting.
This fixes sporadic test failures like
https://github.com/mangrovedao/mangrove-ts/actions/runs/3410881559/jobs/5674398420
and
https://github.com/mangrovedao/mangrove-ts/actions/runs/3411610454/jobs/5676045661
where revert does not do its job.
An alternative fix would be to figure out why we have outstanding requests - but they should not make random tests …

fix(test): Make proxy between tests and anvil to allow closure

---

yarn.lock

build(deps): Bump ansi-regex from 3.0.0 to 3.0.1

---

.github/workflows/node.js.yml

dorny test-reporter now requires the 'checks' write permission, see https://github.com/dorny/test-reporter/issues/229
It seems to have been the case for a while, but for some reason missing permissions are now breaking the build. It might be related to the other weird issues we've seen with Dependabot commits recently.

ci: Add missing permission

---

packages/mangrove.js/src/constants/kandelConfiguration.json
packages/mangrove.js/src/kandel/kandelConfiguration.ts
packages/mangrove.js/src/kandel/kandelDistribution.ts
packages/mangrove.js/src/kandel/kandelDistributionGenerator.ts
packages/mangrove.js/src/kandel/kandelDistributionHelper.ts
packages/mangrove.js/src/kandel/kandelInstance.ts
packages/mangrove.js/src/kandel/kandelSeeder.ts
packages/mangrove.js/src/kandelStrategies.ts
packages/mangrove.js/src/mangrove.ts
packages/mangrove.js/src/semibook.ts
packages/mangrove.js/test/integration/kandel.integration.test.ts
packages/mangrove.js/test/integration/market.integration.test.ts
packages/mangrove.js/test/integration/offermaker.integration.test.ts
packages/mangrove.js/test/integration/semibook.integration.test.ts
packages/mangrove.js/test/unit/kandelCalculator.unit.test.ts
packages/mangrove.js/test/unit/kandelConfiguration.unit.test.ts
packages/mangrove.js/test/unit/kandelDistribution.unit.test.ts
packages/mangrove.js/test/unit/kandelDistributionGenerator.unit.test.ts
packages/mangrove.js/test/unit/kandelDistributionHelper.unit.test.ts

See the title for each commit:
1) use maxuint256 constant from ethers instead of calculating it our selves.
2) add kandelConfiguration - with some initial configuration, better values needed.
3) enable the ability to have constant quote for a distribution like we had constant base
4) enable calculation of a minimum distribution based on the minimum per offer
Note: (4) is a minimum distribution given that we have constant base, constant quote, or constant outgoing. If we allowed varying volume per offer then a smaller total volume could be allowed.

feat(Kandel): Enable retrieval of recommended configuration for Kandel instances

---

packages/mangrove.js/esbuild.mjs
packages/mangrove.js/package.json
packages/mangrove.js/shims/TestMaker.ts
packages/mangrove.js/src/index.ts
yarn.lock

commonlib got resolved from multiple paths, and with the esbuild resolve plugin this only worked if the right import was hit first. That gave sporadic esbuild errors. This change uses absolute paths for the imports. Also removed testMaker shim as it was unused.

fix(esbuild): fix resolving commonlib from multiple paths

---

packages/bot-utils/src/setup.ts

As per the doc https://docs.ethers.org/v5/api/providers/jsonrpc-provider/
> [...] there are also many times where it is known the network cannot change, such as when connecting to an INFURA endpoint, in which case, the StaticJsonRpcProvider can be used which will indefinitely cache the chain ID, which can reduce network traffic and reduce round-trip queries for the chain ID.

feat(bot-utils): Change from default provider to StaticJsonRpcProvider

---

packages/mangrove.js/src/kandel/kandelDistribution.ts
packages/mangrove.js/src/kandel/kandelDistributionGenerator.ts
packages/mangrove.js/src/kandel/kandelDistributionHelper.ts
packages/mangrove.js/src/kandel/kandelInstance.ts
packages/mangrove.js/src/kandel/kandelPriceCalculation.ts
packages/mangrove.js/src/kandel/kandelSeeder.ts
packages/mangrove.js/test/integration/kandel.integration.test.ts
packages/mangrove.js/test/unit/kandelDistribution.unit.test.ts
packages/mangrove.js/test/unit/kandelDistributionGenerator.unit.test.ts
packages/mangrove.js/test/unit/kandelDistributionHelper.unit.test.ts
packages/mangrove.js/test/unit/kandelPriceCalculation.unit.test.ts

Previously prices where generated from minPrice and upwards by multiplying by ratio until we hit maxPrice.
Now, if a midPrice is supplied, we generated outwards from that until we hit minPrice and maxPrice, with a hole at the midPrice.
Note: this required additional changes since multiple places did not support a hole in the list of prices, and for instance the initial provision for a distribution should be for the entire list, and not disregard the hole.

feat(Kandel): Allow price points to be generated outwards from midPrice with a hole

---

packages/mangrove.js/src/kandel/kandelDistribution.ts
packages/mangrove.js/src/kandel/kandelDistributionHelper.ts
packages/mangrove.js/src/kandel/kandelInstance.ts
packages/mangrove.js/test/integration/kandel.integration.test.ts
packages/mangrove.js/test/unit/kandelDistribution.unit.test.ts
packages/mangrove.js/test/unit/kandelDistributionHelper.unit.test.ts

When multiple transactions are needed due to populating many offers, then we first populate those around the mid price (which is indicated via the first ask), and then we radiate outwards.
For retract, we do the reverse, however, retract only supports index ranges, we retract ranges furthest from the mid price, and finally the range centered around the mid price. This means that we can end up using one more tx for retract compared to populate, since the two ranges at the ends cannot be combined.

feat(Kandel): Chunk populate and retract around midprice

---

packages/mangrove.js/src/market.ts
packages/mangrove.js/src/semibook.ts
packages/mangrove.js/test/integration/market.integration.test.ts

We check whether 63/64*gasleft() is > gasreqforposthook  in MgvOfferTaking.makerPosthook, so I think we should use the following instead of just maxGasreqOffer in estimateGas
I think that density and/offer_gasbase are underestimated, possibly due to using TestTokens. So even the above change is not enough. So I propose we simply add the new maxGasreqOffer on top of the existing, that is done in this change.

fix(gas): Increase gas estimation, to account for 64/63 reserved in posthook

---

CHANGELOG.md
src/liquidityProvider.ts
src/market.ts
src/offerLogic.ts
src/util/trade.ts
test/integration/market.integration.test.ts

* fix(offerLogic): Addresses should be checksum addresses when used in comparisons
* feat(trade): Extract getRawParams
* feat(gas): Make gas estimation explicit in orders to allow usage of ethers estimate
* fix(snipe): Do not use gas estimate when sniping
* feat(market): Expose gas estimation functions

feat(gas): Make gas estimation explicit in orders to allow usage of ethers estimate

---

.github/workflows/merge-master-to-develop.yml

Add a wrapper for the reusable workflow which automatically creates, updates or replaces a PR for merging master to develop: https://github.com/mangrovedao/.github/blob/master/workflow-templates/merge-master-to-develop.yml

ci: Create merge-master-to-develop.yml

---

.github/workflows/node.js.yml

Build currently fails because the workflow (specifically, `dorny/test-reporter@v1`) does not have permissions to write the test report.

ci: Add missing permissions for test reports

---

CHANGELOG.md
package.json
yarn.lock

bumps mangrove-core package in mangrove.js. This corresponds to the release of 1.4.7 not 1.4.6 which was erroneously realeased w/o bumping mangrove-core.

mangrove.js v1.4.7

---

CHANGELOG.md
src/offerLogic.ts
test/integration/offermaker.integration.test.ts

This PR reinstates a `LiquidityProvider` getter directly from an `OfferLogic` instance (consistently with the documentation). This introduces two ways to get an LP:
Directly calling via the static `connect` method of the class:
```javascript
const market = await mgv.market({
base: "TokenA",
quote: "TokenB",
bookOptions: { maxOffers: 30 },
});
onchain_lp = await LiquidityProvider.connect(logic, market);
```
or via an offerLogic:
```javascript
const market = await mgv.market({
base: "TokenA",
quote: "TokenB",
bookOptions: { maxOffers: 30 },
});
onchain_lp = await logic.liquidityProvider(market);
```
or directly via a Mangrove instance (for EOAs):
```javascript
eoa_lp = await mgv.liquidityProvider(market);
```

get `LiquidityProvider`  from `OfferLogic`

---

CHANGELOG.md
esbuild.mjs

The resulting mangrove.js conflicts with certain javascript frameworks.
Minification of whitespace and syntax is kept.

fix: Disable esbuild minification of identifiers

---

CHANGELOG.md
src/mgvtoken.ts
test/integration/mgvtoken.integration.test.ts

This PR changes the infinite approvals check from checking against 2^256, to instead check if the allowance is larger than 2^200. This allows for a broader span of "infinite allowance", this is to handle allowance slowly being used when user do Limit and/or Market orders.

fix: infinite approval checks for 2^200

---

package.json
src/configuration.ts
src/constants/mangroveOrder.json
src/kandel/kandelInstance.ts
src/liquidityProvider.ts
src/market.ts
src/offerLogic.ts
src/offerMaker.ts
src/util/trade.ts
test/integration/market.integration.test.ts
test/integration/offermaker.integration.test.ts
test/integration/restingOrder.integration.test.ts
test/unit/configuration.unit.test.ts
yarn.lock

Main change is that offerGasreq is removed.
For now, we define the configuration per network, but we will in the future need pass in arbitrary gasreq for arbitrary underlying routers. I suggest we postpone that change till we have the need.
The chosen configuration is as it was defined in solidity prior to this change (except I add 1 for the mumbai values to use in tests)

feat(upgrade): Upgrade to newest mangrove-strats

---

src/liquidityProvider.ts
src/market.ts
src/util/tickPriceHelper.ts
src/util/tradeEventManagement.ts
test/unit/liquidityProvider.unit.test.ts
test/unit/tickPriceHelper.unit.test.ts

Collected in util TickPriceHelper, at least for now.
Known outstanding tasks
* tickSpacing is not taken into account
* helpers can be used a few more places (goal: raw TickLib should be used through this lib)
* other helpers wrapping TickLib needs to be added, notable tickFromVolumes

feat: price-tick conversion functions

---

.github/workflows/ci.yml

Experiment using `!cancelled()` instead of `always()` as the condition for the `check` job in an attempt to avoid cancelled workflow runs blocking dependabot PR's from merging.
The problem appears to be that the `check` job runs and fails if the workflow is cancelled. Workflow runs are often cancelled automatically when a newer run is triggered. In this case, the branch protection and dependabot should only consider the latest workflow run, not cancelled ones.

ci: Do not run the `check` job if workflow run is cancelled

---

src/util/coreCalculations/TickLib.ts

fix(TickLib): eslint disable no namespace

---

package.json
src/configuration.ts
yarn.lock

When querying deployment addresses, we used the pattern `^${contract package dependency version}` in order to get the latest compatible deployment. However, for pre-releases this resulted in SemVer range patterns of the form `x.y.z-n` which only matches the same or _later_ prereleases, not earlier.
For example, this meant that when mangrove.js depends on mangrove-cove 2.0.0-4, deployments of version 2.0.0-3 would not be matched.
This PR changes the logic for prerelease dependencies such that any deployment of the same major version (*including* prereleases) will be matched.

fix(addresses): Query for any matching pre-release deployment

---

src/market.ts
src/util/tradeEventManagement.ts
test/unit/tradeEventManagement.unit.test.ts

https://app.asana.com/0/0/1205905634724379/f

feat: make totalGave, totalGot, partialFill not undefined

---

src/util/coreCalculations/BinLib.ts
src/util/coreCalculations/TickLib.ts
src/util/coreCalculations/int.ts
test/unit/coreCalculations/binLib.unit.test.ts
test/unit/coreCalculations/coreCalculationsTestUtils.ts

For testing `TickLib.nearestBin` and for later handling of tick spaces, the `TickTreeLib.tick(bin, tickSpacing)` function is needed. The rest of `TickTreeLib` is not needed, so a partial port has been and named `BinLib`.
The tick <-> bin conversion tests from `DynamicBinsTest` has also been ported.
The test uncovered a bug in the port of `nearestBin`: After the Yul assembly code (which only deals with words, ie uints), the bin should be converted to its `int` BigNumber representation, but this wasn't done. This is implicit in Solidity, but must be handled explicitly in the ported code.
This has now been fixed.

feat: Port Bin part of TickTreeLib and tests

---

CHANGELOG.md
src/kandel/coreKandelInstance.ts
src/kandelStrategies.ts
src/liquidityProvider.ts
src/mangrove.ts
src/market.ts
test/integration/mangrove.integration.test.ts

- `Market.Key` type introduced to identify markets (base, quote, tick spacing) in the API.
- Use of `Big(ish)` for `tickSpacing` in a few places has been replaced by `BigNumber(ish)` for consistency with the rest of the API.
- `Mangrove.openMarkets` no longer connects to all markets, but returns a list of `Market.Key`s, optionally with the relevant offer list configuration attached to each. This is identical to the previous `Mangrove.openMarketsData` which has been removed.

feat: Market API simplification & fixes

---

CHANGELOG.md
src/cli/commands/printCmd.ts
src/cli/commands/retractCmd.ts
src/mangroveEventSubscriber.ts
src/market.ts
src/semibook.ts
test/integration/market.integration.test.ts
test/integration/offermaker.integration.test.ts
test/integration/restingOrder.integration.test.ts
test/integration/semibook.integration.test.ts
test/unit/semibook.unit.test.ts
test/util/helpers.ts

The Semibook cache now maintains consistency. After the upgrade to Mangrove v2, the cache could become inconsistent as it was not ensuring that added offers were an extension of the prefix held in the case. This has been fixed.
The Semibook cache now holds complete tick bins: If one offer with a given tick is in the cache, all offers with that tick is in the cache.
The `maxOffers` option in `CacheContentOptions` has been replaced with a new option: `targetNumberOfTicks`.  When loading from chain, the cache will load until at least this number of ticks is in the cache. The default is `Semibook.DEFAULT_TARGET_NUMBER_OF_TICKS`.
A new default value `Semibook.DEFAULT_CHUNK_SIZE` has been introduced for `CacheContentOptions.chunkSize`.

fix: Semibook cache consistency

---

CHANGELOG.md
src/kandel/kandelSeeder.ts
src/liquidityProvider.ts
src/mangrove.ts
src/mangroveEventSubscriber.ts
src/market.ts
src/semibook.ts
src/util/Density.ts
src/util/test/TestMaker.ts
test/integration/kandel/seeder.integration.test.ts
test/integration/market.integration.test.ts
test/integration/offermaker.integration.test.ts
test/integration/semibook.integration.test.ts
test/unit/semibook.unit.test.ts

Mangrove and Semibook configs are now cached on `connect` and (for Semibook) updated by events.
The methods to read configs are no longer async and naming has been made consistent: `Mangrove.config()`, `Market.config()`, and `Semibook.config()`.
Caching the configs limits the RPC requests sent from frequently called methods, in particular `Semibook.simulateMarketOrder` which is used to eg estimate trading volumes and gas.
As part of this change, the following smaller changes have been made:
- Two missing global config fields have been added: `maxRecursionDepth` and `maxGasreqForFailingOffers`.
- All order book events now carry the relevant data for the event. And events that are not related to offers do not carry offer data.
---
- To see the specific tasks where the Asana app for GitHub …

feat: Cache global and local configs

---

CHANGELOG.md
src/market.ts
src/semibook.ts
test/integration/market.integration.test.ts
test/integration/semibook.integration.test.ts
test/util/helpers.ts

The market order simulation used to estimate volumes and gas has been updated to match Mangrove v2's market order logic.
As part of this, `Market.estimateVolume` now also estimates fees and returns it in a new `estimatedFee` field. The existing `estimatedVolume` field is exclusive of fees and thus represents the true amount the taker can expect to receive/pay.

feat: Implement MGV v2 simulateMarketOrder

---

CHANGELOG.md
examples/tutorials/deploy-kandel.js
src/kandel/geometricKandel/geometricKandelDistributionHelper.ts
src/kandel/geometricKandel/geometricKandelStatus.ts
src/kandel/kandelDistribution.ts
src/kandel/kandelDistributionHelper.ts
src/liquidityProvider.ts
src/market.ts
src/semibook.ts
src/util/Density.ts
src/util/tickPriceHelper.ts
src/util/trade.ts
test/integration/cleaner.integration.test.ts
test/integration/kandel/geometricKandelInstance.integration.test.ts
test/integration/market.integration.test.ts
test/integration/restingOrder.integration.test.ts
test/integration/semibook.integration.test.ts
test/unit/kandel/generalKandelDistributionGenerator.unit.test.ts
test/unit/kandel/generalKandelDistributionHelper.unit.test.ts
test/unit/kandel/geometricKandel/geometricKandelDistributionGenerator.unit.test.ts
test/unit/kandel/geometricKandel/geometricKandelDistributionHelper.unit.test.ts
test/unit/kandel/geometricKandel/geometricKandelStatus.unit.test.ts
test/unit/kandel/kandelDistributionHelper.unit.test.ts
test/unit/liquidityProvider.unit.test.ts
test/unit/market.unit.test.ts
test/unit/semibook.unit.test.ts
test/unit/tickPriceHelper.unit.test.ts
test/unit/trade.unit.test.ts
test/util/helpers.ts

Review commit-by-commit, see header.
`feat(tickSpacing): Add rounding up/down` contains the bulk of the rounding changes and some test changes (and a ninja-rename), but subsequent commits add more tests.
Semibook changes are not tested as we have no unit tests for the changed functions and we have no market with tickSpacing>1

feat(tickSpacing): Round up, down, or to nearest depending on scenario

---

CHANGELOG.md
package.json
src/mangrove.ts
yarn.lock

- feat: Add `Mangrove.getRestingOrderRouterAddress` which gets the address of the router contract for resting orders belonging to the connected user (`Mangrove.signer`).
- Upgrade to mangrove-deployments v2.0.1-2

feat: Add Mangrove.getRestingOrderRouterAddress and update mangrove-deployments to 2.0.1-2

---

CHANGELOG.md
src/market.ts
test/integration/market.integration.test.ts

Rename `Market.close()` to `Market.disconnect()` to more clearly signal that it's dual to `Market.connect()` and does not close the market on Mangrove.

feat!: Rename Market.close to disconnect

---

CHANGELOG.md
src/amplifier/mangroveAmplifier.ts
src/logics/AbstractRoutingLogic.ts
src/mangrove.ts
src/market.ts
test/integration/market.integration.test.ts
test/integration/restingOrder.integration.test.ts

`SimpleAaveLogic` is not available on Blast Sepolia, so mangrove.js threw an error when it tried to get the address and create the routing logic.
This PR therefore makes SimpleAaveLogic optional. If the address isn't found for a network, that routing logic isn't available.

fix: Make SimpleAaveLogic optional

---

CHANGELOG.md
src/constants/kandelConfiguration.json
test/unit/kandel/kandelConfiguration.unit.test.ts

This will prevent the SDK from breaking when used on a market for which there is not Kandel configuration.
The values may not be ideal, but the user can override if needed.
Also add initial configuration for Blast and Blast Sepolia. For now, they use the defaults, so have only be added to make it easy to find and modify later if needed.

feat(kandel): Add defaults for minimum{Base,Quote}PerOfferFactor

---

CHANGELOG.md
src/amplifier/mangroveAmplifier.ts
src/index.ts
src/kandel/kandelSeeder.ts
src/market.ts
src/util/trade.ts
src/util/transactions.ts

Also fixes the doc generation issue of `MangroveAmplifier` referencing a type that is not included in the docs.

feat: Move Transaction type from Market to util/transactions
