packages/cleaning-bot/src/MarketCleaner.ts

All the calculations in Market.ts are on integers, so no reason to use Big, especially because we then avoid some conversions from BigNumber to Big.

cleaning-bot: Use BigNumber instead of Big

---

.github/workflows/node.js.yml

To speed up tests, while we focus on a Polygon release.

Etherium mainnet tests disabled for a while

---

packages/obfiller-bot/config/mumbai.json

Mumbai specific configuration file added to support this.

obfiller-bot: Disable WETH/USDC market on Mumbai

---

packages/mangrove-solidity/test/test-offerProxy.js

Hopefully addresses some of the flaky test issues in `Deploy offerProxy`, see #109.

mangrove-solidity: Fix some missing/misordered tx.wait()

---

packages/mangrove.js/cli/commands/parrotCmd.ts

All addresses are now compared to what is in the repo:
- notes are generated for addresses that are not in the repo (e.g. addresses of external contracts such as WETH)
- warnings are generated for addresses that differ from the one in the repo
Also, the printed address overview table now includes all components.
EXAMPLE OUTPUT:
```shell
$ mgv parrot
WARNINGS
config, repo: Mangrove is not configured to use the latest MgvOracle contract - globalConfig.useOracle=false, globalConfig.monitor=0x0000000000000000000000000000000000000000, address of MgvOracle=0xA7F318d18d163E4677A4eAc2ffd820bA0c605EB7
NOTES
mangrove.js, repo: Found address for 'DAI' which is not in repo - address in component=0x001B3B4d0F3714Ca98ba10F6042DaEbF0B1B7b6F
mangrove.js, repo: Found address for 'USDC' which is not in …
```

mangrove.js: Analyse all addresses in `mgv parrot`

---

packages/mangrove.js/src/market.ts
packages/mangrove.js/src/semibook.ts
packages/mangrove.js/test/integration/market.integration.test.ts
packages/mangrove.js/test/integration/semibook.integration.test.ts

feat!(semibook): make `estimateVolume` async and fetch more offers if cache is insufficient

---

packages/cleaning-bot/src/MarketCleaner.ts
packages/mangrove.js/src/cli/commands/printCmd.ts
packages/mangrove.js/src/cli/commands/retractCmd.ts
packages/mangrove.js/src/liquidityProvider.ts
packages/mangrove.js/src/market.ts
packages/mangrove.js/src/semibook.ts
packages/mangrove.js/test/integration/market.integration.test.ts
packages/obfiller-bot/src/OfferMaker.ts
packages/obfiller-bot/src/OfferTaker.ts

feat!(market): Remove deprecated `MarketBook` and replace uses with `Book`

---

packages/mangrove.js/src/constants.ts
packages/mangrove.js/src/mangrove.ts
packages/mangrove.js/src/mgvtoken.ts
packages/mangrove.js/test/integration/mgvtoken.integration.test.ts

Add MgvToken.toFixed method for easy displaying of amounts

---

packages/mangrove-solidity/scripts/governance/MGVActivateMarkets.js

Mangrove activation script no longer needs helper.js

Simplifying activation script for Mangrove

---

packages/mangrove.js/package.json

Was missed in @8bf43fa9cc438f2af299d8afb06146a11dbe5f4c

fix: Update mangrove.js package version to 0.3.7

---

packages/mangrove.js/src/index.ts

export displayedDecimals and defaultDisplayedDecimals

---

packages/mangrove.js/src/index.ts

This reverts commit 9b507c9426db2b73fc58c3fdd541ed060a086e20.

Revert "export displayedDecimals and defaultDisplayedDecimals"

---

.github/scripts/address-handling.js
.github/scripts/package.json
.github/scripts/write-addresses-json.js

Extracted common functionality for coming CI automation into module.

feat(ci): upgrade write-addresses-json

---

.github/workflows/updateadr.yml

feat(ci): Fix working-directory again

---

.github/workflows/updateadr.yml

Oh lord, why hast thou forsaken me?

feat(ci): Fix broken path

---

packages/bot-maker-noise/src/OfferMaker.ts
packages/bot-maker-noise/src/index.ts

Stop the `OfferMaker`s instead and let NodeJS handle shutdown when there's no more work instead of calling `process.exit`.
This allows any logging to complete before closing down.

feat(Noise Maker): Shutdown `OfferMaker`s and app gracefully

---

packages/bot-taker-greedy/src/OfferTaker.ts

Attempt at avoiding that the bot gets stuck

refactor: Don't log token balances

---

packages/commonlib.js/src/logger.ts

fix: repair loglevel attribution

---

.github/workflows/automerge-dependabot-prs.yml

ci: Automerge dependabot patch updates

---

.github/workflows/node.js.yml

prepare master so workflow for merge of `feature/foundry` works

chore: add foundry and recursive checkout to workflow

---

.env.local.example
README.md
packages/mangrove-solidity/package.json
yarn.md

Should now be a bit more detailed wrt. getting started, and details around yarn are moved to separate doc. For now yarn documentation is kept in the repo, pending furhter work on docs.

feat(doc): Updated readme after setting up dev environment

---

.github/workflows/node.js.yml

Using Action alls-green to have one single job to check for a green workflow.

feat(ci): Introduce final "check" job

---

packages/mangrove.js/src/semibook.ts

Closes #620.
Summary: mangrove.js now faithfully simulates mangrove's solidity execution engine. The `estimateVolume` function has been changed and includes a new `boundary` parameter.
If `params.to == buy`, then the mapping to solidity code is:
* `params.given` --> `takerWants`
* `params.boundary` --> `takerGives`
Otherwise if `params.to == sell`, then the mapping is:
* `params.given` --> `takerGives`
* `params.boundary` --> `takerWants`
You can omit the `estimateVolume`'s `boundary` param and use it like before. It will automatically set a very high max avg. price when buying, and a 0 min avg. price when selling.

feat(mangrove.js): generalize volume estimations (#620)

---

packages/mangrove-solidity/src/Mangrove.sol

* detail how tokens with transfer fees don't interact well with Mangrove
* remove a token type which is not well-defined because I don't remember what token I was talking about

doc(mangrove-solidity): detail comment on incompatible token types

---

foundry.toml

You can say --rpc-url mumbai and --etherscan-api-key mumbai

feat: use new foundry keys feature

---

packages/mangrove-solidity/src/strategies/offer_forwarder/abstract/Forwarder.sol

Removing redundant locals fixed it

fix(build): forge coverage fails due to long stack

---

packages/mangrove.js/src/offerLogic.ts

otherwise you could try to talk to a nonexistent contract

fix(js): await deployment before returning

---

packages/mangrove-solidity/script/MangroveJs.s.sol
packages/mangrove.js/src/market.ts
packages/mangrove.js/src/util/tradeEventManagement.ts
packages/mangrove.js/test/integration/market.integration.test.ts
packages/mangrove.js/test/integration/offermaker.integration.test.ts
packages/mangrove.js/test/integration/restingOrder.integration.test.ts
packages/mangrove.js/test/integration/semibook.integration.test.ts
packages/mangrove.js/test/util/helpers.ts

OfferWriteEvent-parsing did not use the right inbound/outbound.
Also change decimals of TokenB to 6 to catch errors due to wrong decimals.

fix(restingOrder): wrong decimals for resting orders

---

packages/mangrove.js/src/constants.ts
packages/mangrove.js/test/integration/mgvtoken.integration.test.ts

Commit 6f7a26b37efcd9bbf777e65ed9683eca2d820651 accidentally reverted prior fix.

fix(restingOrder): Reapply fix from 6be1df52f557d6f16be59b1fd700ebe1597e357e

---

packages/mangrove.js/src/semibook.ts

fix: roundup instead of adding 1 in market simulation

---

.github/workflows/node.js.yml

Conflicts with our usage of the checks step as branch protection.

ci: remove paths-ignore

---

.github/workflows/automerge-dependabot-prs.yml

dependabot changed - we try to chase it.

ci: Update automerge dependabot PR

---

packages/mangrove.js/test/integration/market.integration.test.ts

This reverts commit abb385860cba5bd1cd49d1ce99153e349adc22a5.

Revert "feat(monitoring): Test master failure (#943)"

---

packages/mangrove.js/src/kandel/kandelDistribution.ts
packages/mangrove.js/src/kandel/kandelDistributionGenerator.ts
packages/mangrove.js/src/kandel/kandelInstance.ts
packages/mangrove.js/src/kandel/kandelStatus.ts
packages/mangrove.js/src/util/node.ts
packages/mangrove.js/src/util/test/mochaHooks.ts
packages/mangrove.js/test/integration/kandel.integration.test.ts
packages/mangrove.js/test/integration/market.integration.test.ts
packages/mangrove.js/test/unit/kandelDistribution.unit.test.ts
packages/mangrove.js/test/unit/kandelDistributionGenerator.unit.test.ts
packages/mangrove.js/test/unit/kandelStatus.unit.test.ts
packages/mangrove.js/test/unit/prettyPrint.unit.test.ts

logging: Reduce noise during tests
KandelStatus: Add min and max price
KandelInstance: Add calculateUniformDistributionFromMinPrice to heal all dead offers
KandelInstance: Add getMinimumVolumeForIndex to heal a single offer

feat(Kandel): Add functions for healing offers

---

packages/mangrove.js/examples/tutorials/deploy-kandel.js
packages/mangrove.js/src/constants/kandelConfiguration.json
packages/mangrove.js/src/kandel/kandelInstance.ts
packages/mangrove.js/src/kandelStrategies.ts
packages/mangrove.js/src/liquidityProvider.ts
packages/mangrove.js/src/mangrove.ts
packages/mangrove.js/src/market.ts
packages/mangrove.js/src/offerLogic.ts
packages/mangrove.js/test/integration/kandel.integration.test.ts
packages/mangrove.js/test/integration/market.integration.test.ts
packages/mangrove.js/test/integration/offermaker.integration.test.ts

* chore(OfferLogic): Refactor getMissingProvision for offerLogic and liquidityProvider
* fix(Kandel): make recommended config just default
* feat(Kandel): Add getMissingProvisionFromOffers
* fix(Kandel): Update kandelConfiguration based on latest knowledge
Also fixes https://github.com/mangrovedao/mangrove-ts/issues/557

feat(Kandel): Add getMissingProvisionFromOffers

---

CHANGELOG.md
src/liquidityProvider.ts
src/util/prettyPrint.ts

Fixing pretty printing bug due to console.table not pretty printing objects correctly

fix [object] being pretty printed when calling consoleAks/Bids.

---

esbuild.mjs
shims/logger.ts

Shim-setup made it impossible to enable logging.

fix(logger): Fix enableLogging in browser-context

---

src/market.ts
test/unit/market.unit.test.ts

Function is unused after changes to tick.

Remove Market.getPrice

---

.husky/pre-commit
.yarnrc.yml
package.json

Removes some vestiges from the deprecated monorepo setup.

fix(build): Remove monorepo vestiges

---

test/mocha/config/integration-tests.json

Required for less-than-stellar dev boxes.

fix(tests): Increase timeout for integration tests

---

src/util/trade.ts

Initial work on improving getParams-methods in trade. (More improvements to come.)

feat(trade): factor out slippage calc from getParams-methods

---

src/semibook.ts

NOTE: Non-functional, right now.

feat(semibook) Reintroduce optional boundary on VolumeParams

---

src/util/trade.ts
test/integration/market.integration.test.ts
test/integration/restingOrder.integration.test.ts
test/unit/trade.unit.test.ts

Also fix and add to the test suite.

Fix getParamsForBuy and -Sell in trade

---

src/constants/mangroveOrder.json
test/unit/configuration.unit.test.ts

Computed using data from:
https://github.com/mangrovedao/mangrove-strats/pull/155

feat: update take overhead

---

CHANGELOG.md
examples/tutorials/deploy-kandel.js
src/kandel/kandelSeeder.ts
src/market.ts
src/util/trade.ts
test/integration/kandel/coreKandelInstance.integration.test.ts
test/integration/kandel/farm.integration.test.ts
test/integration/kandel/geometricKandelInstance.integration.test.ts
test/integration/kandel/maxOffersInChunk.integration.test.ts
test/integration/kandel/seeder.integration.test.ts
test/integration/restingOrder.integration.test.ts

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205905634724382

feat: Add `retractRestingOrder` method to Market

---

CHANGELOG.md
package.json

Published by GitHub user: lnist

chore: Publish npm package v2.0.0
